### ISSUE TITLE
Migrations et dump.json difficiles d'accès

### ISSUE THREAD

**Issue by tanguy-perennou** [BFHENG/topoguide-baptiste-heng#1]
Merci de fusionner toutes les branches de manière à mettre les migrations et dump.json dans la branche main

**Comment by BFHENG** [comment]
Bonjour,

En tapant git branch sur VSCode au niveau de mon projet, je ne vois que la
branche main.
De plus, il m'indique que tout a bien été commit (migration + dump).
Comment faire ?

Merci et bonne journée,
Baptiste

Le dim. 24 avr. 2022 à 21:55, Tanguy Pérennou ***@***.***> a
écrit :

**Comment by tanguy-perennou** [comment]
Tu as peut être oublié un push ? Sinon, fais simplement un dump.json et un push.

**Comment by BFHENG** [comment]
Je viens de push dump.json.

Prévenez moi si vous ne parvenez toujours pas à y accéder.


Le lun. 25 avr. 2022 à 09:41, Tanguy Pérennou ***@***.***> a
écrit :

**Comment by tanguy-perennou** [comment]
Tout est là, je ferme le ticket !
